name: GitHub Pages deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5

      - name: Set up PNPM
        uses: pnpm/setup@v1
        with:
          version: 11
          runtime: node@22
          cache: true

      - name: Build my App
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "./dist"

      - name: Deploy 🚀
        id: deployment
        uses: actions/deploy-pages@v4
